FROM arm64v8/debian:bullseye-slim AS runner
RUN apt update -y && \
    apt install curl gnupg2 ca-certificates unzip supervisor net-tools procps --no-install-recommends -y && \
    groupadd -g 2222 zerotier-one && \
    useradd -u 2222 -g 2222 zerotier-one && \
    curl -sL -o ztone.sh https://install.zerotier.com && \
    bash ztone.sh && \
    rm -f ztone.sh && \
    apt clean -y && \
    rm -rf /var/lib/zerotier-one && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /opt/key-networks/ztncui
COPY build/artifact.zip .
RUN unzip ./artifact.zip && \
    rm -f ./artifact.zip

COPY buildsrc/binaries/gosu /bin/gosu
COPY buildsrc/binaries/minica /usr/local/bin/minica
COPY buildsrc/binaries/argon2g /usr/local/bin/argon2g
COPY buildsrc/binaries/fileserv /usr/local/bin/gfileserv

COPY start_zt1.sh /start_zt1.sh
COPY start_ztncui.sh /start_ztncui.sh
COPY supervisord.conf /etc/supervisord.conf

RUN chmod 0755 /bin/gosu && \
    chmod 0755 /usr/local/bin/minica && \
    chmod 0755 /usr/local/bin/argon2g && \
    chmod 0755 /usr/local/bin/gfileserv && \
    chmod 0755 /start_*.sh

EXPOSE 3000/tcp
EXPOSE 3180/tcp
EXPOSE 8000/tcp
EXPOSE 3443/tcp
EXPOSE 9993/udp

WORKDIR /
VOLUME ["/opt/key-networks/ztncui/etc"]
VOLUME [ "/var/lib/zerotier-one" ]
ENTRYPOINT [ "/usr/bin/supervisord" ]

